services:
  db:
    image: mariadb:11
    restart: unless-stopped
    container_name: mariadb-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=playground

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: mariadb-phpmyadmin
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
