services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    restart: unless-stopped
    container_name: mssql-db
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "yourStrong(!)Password", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 1433:1433
    volumes:
      - ./data/mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
